# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.104.0"

default_platform :ios

platform :ios do
	before_all do
		# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
		ascii_art(image_path: 'kllect/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png', width: 60)
		cocoapods
	end

	lane :test do |options|
		scan(workspace: "kllect.xcworkspace",
			 scheme: "kllect",
			 devices: ['iPhone 6s'],
			 clean: true,
			 skip_build: options[:skip_build],
			 code_coverage: true,
			 skip_slack: true
		)
	end

	lane :build do
		gym(scheme: "kllect",
			include_symbols: true,
			workspace: "kllect.xcworkspace"
		)
	end

	desc "Submit a new Beta Build to Apple TestFlight"
	desc "This will also make sure the profile is up to date"
	lane :beta do
		xcversion version: "~> 8.0"
		ensure_git_status_clean
		increment_build_number
		badge
		build
		test(skip_build: true)
		pilot(distribute_external: false)
		clean_build_artifacts
		commit_version_bump
		push_to_git_remote
		rocket
	end

	after_all do |lane|
		# This block is called, only if the executed lane was successful

		# slack(
		#	 message: "Successfully deployed new App Update."
		# )
	end

	error do |lane, exception|
		# slack(
		#	 message: exception.message,
		#	 success: false
		# )
	end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
